-- 跑腿代办模块数据库迁移（在目标 MySQL 数据库执行一次）
CREATE TABLE IF NOT EXISTS `errand_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `publisher_id` BIGINT NOT NULL COMMENT '发布者用户 ID',
  `runner_id` BIGINT NULL COMMENT '接单者用户 ID',
  `title` VARCHAR(80) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `pickup_location` VARCHAR(255) NOT NULL,
  `delivery_location` VARCHAR(255) NOT NULL,
  `distance_km` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  `weight_kg` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  `urgent` TINYINT NOT NULL DEFAULT 0 COMMENT '0普通 1加急',
  `contact_phone` VARCHAR(32) NULL,
  `price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1待接单 2已接单 3进行中 4待确认 5已完成 6已取消',
  `payment_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0未支付 1已支付 2已退款',
  `audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0待审核 1通过 2驳回',
  `audit_remark` VARCHAR(255) NULL,
  `accepted_time` DATETIME NULL,
  `paid_time` DATETIME NULL,
  `completed_time` DATETIME NULL,
  `cancelled_time` DATETIME NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_errand_available` (`audit_status`, `status`, `urgent`, `create_time`),
  KEY `idx_errand_publisher` (`publisher_id`, `create_time`),
  KEY `idx_errand_runner` (`runner_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
